version: "3"
services:

  rabbitmq:
    container_name: rabbitmq
    image: bitnami/rabbitmq:latest
    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: password
    ports:
      - "15672:15672"

  init-rabbitmq:
    container_name: init-rabbitmq
    image: softonic/rabbitmqadmin
    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: password
    volumes:
      - ./:/home:Z
    depends_on:
      - rabbitmq
    command: "/home/test.init.sh"

  client:
    container_name: client
    build:
      context: ./client
    image: client:latest
    environment:
      JAR_NAME: client-0.0.1-SNAPSHOT.jar
    depends_on:
      - rabbitmq

  server:
    container_name: server
    build:
      context: ./server
    image: server:latest
    environment:
      JAR_NAME : server-0.0.1-SNAPSHOT.jar
    depends_on:
      - rabbitmq





