apiVersion: v1
kind: ConfigMap
metadata:
  name: manager-config
  namespace: spring-batch
data:
  application-docker.yml: |
    spring:
      rabbitmq:
        host: rabbit-service.rabbit-srv
        virtual-host: spring-batch
        port: 5672
        username: sb-user
        password: sb-user

      datasource:
        url: jdbc:postgresql://postgres-service.postgres-srv:5432/sbdb?tcpKeepAlive=true&currentSchema=sbdb
        username: sb-user
        password: sb-user
        initialization-mode: always
        driver-class-name: org.postgresql.Driver
        continue-on-error: false
      
      batch:
        initialize-schema: always
        job:
          enabled: false

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: spring-batch
data:
  application-docker.yml: |
    spring:
      rabbitmq:
        host: rabbit-service.rabbit-srv
        virtual-host: spring-batch
        port: 5672
        username: sb-user
        password: sb-user
      jpa:
        hibernate:
          ddl-auto: update
      datasource:
        url: jdbc:postgresql://postgres-service.postgres-srv:5432/sbdb?tcpKeepAlive=true&currentSchema=sbdb
        username: sb-user
        password: sb-user
        driver-class-name: org.postgresql.Driver
        initialization-mode: always
        continue-on-error: true
      batch:
        initialize-schema: always
