kind: Deployment
apiVersion: apps/v1
metadata:
  name: manager-deployment
  namespace: spring-batch
spec:
  replicas: 1
  selector:
    matchLabels:
      selector_label: sb-manager
  template:
    metadata:
      name: manager-pod
      labels:
        selector_label: sb-manager
    spec:
      containers:
        - name: manager-pod
          image: "mahasiah:32188/spring-batch-manager:latest"
          imagePullPolicy: Always
          env:
            - name: JAR_NAME
              value: "manager-0.0.1-SNAPSHOT.jar"
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: manager-config
              mountPath: /app/config/application-docker.yml
              subPath: application-docker.yml
              readOnly: true
      volumes:
        - name: manager-config
          configMap:
            name: manager-config
