version: '3'
services:
  iptables-test-front:
    image: iptables-test-front
    build:
      context: .
      dockerfile: front/Dockerfile
    network_mode: "host"
    restart: always
    cap_add:
      - NET_ADMIN

  iptables-test-accept:
    image: iptables-test-accept
    build:
      context: .
      dockerfile: test/Dockerfile
    environment:
      listenport: 9999
    ports:
      - "9999:9999"
    cap_add:
      - NET_ADMIN
    restart: always

  iptables-test-reject:
    image: iptables-test-reject
    build:
      context: .
      dockerfile: test/Dockerfile
    environment: 
      listenport: 6666      
    ports:
      - "6666:6666"
    cap_add:
      - NET_ADMIN
    restart: always


    
